# NumPy

### (1) Checking dimension of array

In [1]:
import numpy as np

In [2]:
a = np.array(1)
print("Dimension is :",a.ndim)

Dimension is : 0


In [3]:
a1 = np.array([1,2,3,4,5])
print("Dimension is :",a1.ndim)

Dimension is : 1


In [4]:
a2 = np.array([[1,2,3,4,5]])
print("Dimension is :",a2.ndim)

print("**********************")

a22 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(a22)
print("Dimension is :",a22.ndim)

Dimension is : 2
**********************
[[1 2 3 4 5]
 [6 7 8 9 0]]
Dimension is : 2


In [5]:
a3 = np.array([[[1,2,3,4,5]]])
print("Dimension is :",a3.ndim)

print("**********************")

a33 = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[41,51,61]]])
print(a33)
print("Dimension is :",a33.ndim)

Dimension is : 3
**********************
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [41 51 61]]]
Dimension is : 3


### (2) Concatenation

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Addition is :",arr[3]+arr[7])

Addition is : 12


In [7]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

p1 = int(input("Index 1 ="))
p2 = int(input("Index 2 ="))

print("Addition is :",arr1[p1]+arr1[p2])
print("Substraction is :",arr1[p1]-arr1[p2])
print("Multiplication is :",arr1[p1]*arr1[p2])
print("Division is :",arr1[p1]/arr1[p2])

Index 1 =3
Index 2 =8
Addition is : 13
Substraction is : -5
Multiplication is : 36
Division is : 0.4444444444444444


### (3) Shape

In [8]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
array.shape

(10,)

In [10]:
ar1 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
ar1

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [11]:
ar1.shape

(2, 5)

In [12]:
ar2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
ar2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
ar2.shape

(2, 2, 3)

In [14]:
ar3 = np.array([[[[11,12,13],[14,15,16]],[[17,18,19],[20,21,22]]],[[[11,12,13],[14,15,16]],[[17,18,19],[20,21,22]]]])
ar3

array([[[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]],


       [[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]]]])

In [15]:
ar3.shape

(2, 2, 2, 3)

### (4) Reshape

### 1D Array

In [16]:
Arr = np.array([21,22,23,24,25,26,27,28,29,30])
Arr.reshape(1,10)

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [17]:
Arr.reshape(10,1)

array([[21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30]])

In [18]:
Arr.reshape(2,5)

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
Arr.reshape(5,2)

array([[21, 22],
       [23, 24],
       [25, 26],
       [27, 28],
       [29, 30]])

In [20]:
Ar1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(Ar1)
print("Length of array ::",len(Ar1))

print("**************************")
print("Reformation of Array :")
r = int(input("Rows ="))
c = int(input("Columns ="))

print("**************************")
print(Ar1.reshape(r,c))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Length of array :: 20
**************************
Reformation of Array :
Rows =5
Columns =4
**************************
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


### 2D Array

In [21]:
Ar2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(Ar2)
print("Shape of array :",Ar2.shape)
print("Length of array ::",len(Ar2))

print("**************************")
print("Reformation of Array :")
r = int(input("Rows ="))
c = int(input("Columns ="))

print("**************************")
print(Ar2.reshape(r,c))

[[1 2 3 4 5]
 [6 7 8 9 0]]
Shape of array : (2, 5)
Length of array :: 2
**************************
Reformation of Array :
Rows =5
Columns =2
**************************
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


### 3D Array

In [22]:
Ar3 = np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[1,2,3,4,5],[6,7,8,9,0]]])
print(Ar3)
print("Shape of array :",Ar3.shape)
print("Length of array ::",len(Ar3))

print("**************************")
print("Reformation of Array :")
r = int(input("Rows ="))
c = int(input("Columns ="))

print("**************************")
print(Ar3.reshape(r,c))

[[[1 2 3 4 5]
  [6 7 8 9 0]]

 [[1 2 3 4 5]
  [6 7 8 9 0]]]
Shape of array : (2, 2, 5)
Length of array :: 2
**************************
Reformation of Array :
Rows =2
Columns =10
**************************
[[1 2 3 4 5 6 7 8 9 0]
 [1 2 3 4 5 6 7 8 9 0]]
